apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lj074s6dt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lj074s6dt-go 
  name: lj074s6dt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lj074s6dt-go 
